### ISSUE TITLE
Code about baselines

### ISSUE THREAD

**Issue by EchoTHChen** [tedyhabtegebrial/SoftOcclusionMSI#1]
It is a great work! I'm very interested in this paper and the source code. I just start studying novel view synthesis for panoramas and get stuck in re-implement the baselines. Could you also release your baselines (such as S-NeRF, I notice that S-NeRF get some good results  in some cases)? Thanks!

**Comment by tedyhabtegebrial** [comment]
Hi,

S-NeRF will be released to this repository. I will reply here when it is ready

**Comment by EchoTHChen** [comment]
Thanks so much! I wonder when roughly do you plan to release the code for the baseline? (i hope I did not offend you)



---Original---
From: "Tewodros ***@***.***&gt;
Date: Mon, Jul 11, 2022 15:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tedyhabtegebrial/SoftOcclusionMSI] Code about baselines (Issue#1)




 
Hi,
 
S-NeRF will be released to this repository. I will reply here when it is ready

**Comment by tedyhabtegebrial** [comment]
No worries ;) It should be released within this week.

**Comment by Eric-chuan** [comment]
hi, sorry to interrupt, but is there any progress on the release of the baseline code?

**Comment by tedyhabtegebrial** [comment]
Hi Eric,

could you please pull the main branch and run the following to train S-NeRF.

```
cd baselines/s_nerf_pl
./scripts/residential.sh
```

 There are pre-trained models in the google drive folder. If you download them, you can evaluate them using the test scripts
 ```
./scripts/residential_test.sh
```

**Comment by EchoTHChen** [comment]
> 

Thanks for your sharing!

**Comment by tedyhabtegebrial** [comment]
No problem. Could you please let me know if it works for you or if there are some bugs ?

**Comment by EchoTHChen** [comment]
Sorry to bother you again. I wonder when roughly do you plan to release the baseline, MatryODShka, under your experiment setting?

**Comment by EchoTHChen** [comment]
thanks for your nice and quick reply!



---Original---
From: "Tewodros ***@***.***&gt;
Date: Mon, Jul 11, 2022 15:16 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tedyhabtegebrial/SoftOcclusionMSI] Code about baselines (Issue#1)




 
No worries ;) I should be released within this week.

**Comment by tedyhabtegebrial** [comment]
Sorry,  I am out of my lab at the moment.
We haven’t released the MatryODShka baseline. Do you still need it?

**Comment by EchoTHChen** [comment]
> Sorry, I am out of my lab at the moment. We haven’t released the MatryODShka baseline. Do you still need it?

Yes

**Comment by EchoTHChen** [comment]
Ok，i will run it later. If&nbsp; I have any question，I will open a new issue. Thanks for your help and nice reply.



---Original---
From: "Tewodros ***@***.***&gt;
Date: Fri, Jul 22, 2022 00:24 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [tedyhabtegebrial/SoftOcclusionMSI] Code about baselines (Issue#1)




 
No problem. Could you please let me know if it works for you or if there are some bugs ?

**Comment by tedyhabtegebrial** [comment]
Okay, working on the MatryODShka baselines now. Please come back in sometime. I would appreciate it greatly if you could test run the code let me know if it works fine or not

**Comment by EchoTHChen** [comment]
thanks！



---Original---
From: ***@***.***&gt;
Date: Tue, Oct 11, 2022 17:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tedyhabtegebrial/SoftOcclusionMSI] Code about baselines (Issue#1)




 
Okay, working on the MatryODShka baselines now. Please come back in sometime. I would appreciate it greatly if you could test run the code let me know if it works fine or not

**Comment by tedyhabtegebrial** [comment]
Please, check **baseline/mods**
