### ISSUE TITLE
How to adapt the code for new scenes with poses? 

### ISSUE THREAD

**Issue by EchoTHChen** [tedyhabtegebrial/SoftOcclusionMSI#3]
I have several datasets(wide-baseline) which are captured about 1.0 meter between two neighbor views. I have the poses of the datasets but I do not know how to adapt the code to run on my own data with poses. Could you tell me how to revise the code?

**Comment by tedyhabtegebrial** [comment]
Hi, you will have to update the following functions: ``` cartesian_2_spherical, spherical_2_cartesian, spherical_2_equi,  ``` and ``` equi_2_spherical ``` in the [src/utils.py](/src/utils.py ) file. These functions need to change based on: _the way the coordinate systems are defined in your dataset_ and _the way $\theta$ and $\phi$ are defined on the Equirectangular projection image_. For the coordinate system details in our existing datasets, please check [datasets](/docs/data/dataset.md).

**Comment by tedyhabtegebrial** [comment]
Lastly, make sure you are importing and add your new dataset class in the ```get_dataset``` function in [data/__init__.py](data/__init__.py).

**Comment by EchoTHChen** [comment]
Thanks!
