### ISSUE TITLE
How to transform spherical images and poses into the perspective images and poses for Residential Dataset?

### ISSUE THREAD

**Issue by EchoTHChen** [tedyhabtegebrial/SoftOcclusionMSI#6]
Hi! I'm very interested in your paper and your datasets. And I’m studying how to relate the perspective image and poses with spherical images and poses. I have read your paper and corresponding supplementary. But I still do not understand how to get perspective poses and rgbs from spherical image and how to transform perspective poses back into spherical poses specifically. Could you share your preprocessing code about Coffee Area?

**Comment by EchoTHChen** [comment]
Do you know how to transform the spherical images and poses into perspective images and poses for Residential Dataset? I want to run perspective methods (such as perspective NeRF, pixelnerf) on Residential Dataset and render spherical image (query by shooting spherical rays instead of perspective rays). It would be even better if you could share your detailed code about transform the spherical images and poses into perspective images and poses for Residential Dataset (Or Could you tell me about how to get their original perspective images and poses when you synthesize the dataset)

**Comment by tedyhabtegebrial** [comment]
Hi, I have shared the code via email. Closing it for now.

**Comment by zjulabwjt** [comment]
> Hi, I have shared the code via email. Closing it for now.

@tedyhabtegebrial @EchoTHChen Hi,Thanks for your great work! I also have same problem, Could you share your preprocessing code to me? Thanks for your help!

**Comment by thucz** [comment]
> > Hi, I have shared the code via email. Closing it for now.
> 
> @tedyhabtegebrial @EchoTHChen Hi,Thanks for your great work! I also have same problem, Could you share your preprocessing code to me? Thanks for your help!

See the processing code in this [link](https://github.com/thucz/PanoGRF/tree/main/dataset/residential_make)
