### ISSUE TITLE
Question about alpha

### ISSUE THREAD

**Issue by kimkj38** [tedyhabtegebrial/SoftOcclusionMSI#7]
Hello. Thanks for your great work first and I have a question.

I'm confused about alpha because it is transparency in your paper but opacity in the referenced paper [[1]MatryODShka: Real-time 6DoF Video View Synthesis using Multi-Sphere Images](https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123460426.pdf) 

I think opacity is right because weight should be bigger when the certain point is opaque. What is the difference between your paper and the referenced paper? 

<img width="502" alt="image" src="https://github.com/tedyhabtegebrial/SoftOcclusionMSI/assets/76815825/ae60eda3-d7c0-4bc3-a79c-5bdbac7f3bd3">

**Comment by tedyhabtegebrial** [comment]
Hi,

We used the term transparency loosely, **1-alpha** is actually the transparency and you are right **alpha** is an opacity term.

Best

**Comment by kimkj38** [comment]
@tedyhabtegebrial Thanks for your reply!
